Changes not included in the last commit

diff --git a/alien_clear_outputdir b/alien_clear_outputdir
--- a/alien_clear_outputdir
+++ b/alien_clear_outputdir
@@ -1,3 +1,11 @@
 #!/bin/sh
 
-exec alien_rmdir /alice/cern.ch/user/y/ylai/workdir/outputdir
+alien_macro="runCalibEmcal.C"
+if grep -q terminate "$alien_macro"; then
+    echo "error: $alien_macro is in mode \`terminate'"
+    exit 1
+fi
+
+output_dir="/alice/cern.ch/user/y/ylai/workdir/\
+$(sed "/SetGridOutputDir/!d;s/.*(\"//;s/\").*//" < "$alien_macro")"
+exec alien_rmdir "$output_dir"
